### PR TITLE
Rename the command entrypoint from `run` back to `main`.

### PR DESCRIPTION
**Pull request by sunfishcode**
LLVM has special handling for functions named `main`, which we need to avoid because we're creating the component-level `main` rather than the C-level `main`. To do this, write the `main` function in assembly, which is fortunately very simple now.

### CODE REVIEW

**Review by pchickey — APPROVED** [review]
Awesome! Thank you for fixing this :)

**Comment by sunfishcode** [comment]
We are also going to need a toolchain change here, so that users generating components directly don't hit this.

**Comment by pchickey** [comment]
Agreed, we need a toolchain fix in order to land a wasi-libc and/or std that targets preview 2 directly. But, we can merge this in the meantime, correct?

**Comment by sunfishcode** [comment]
Yep.

**Pull request merged**
