### PR TITLE
fix: symlink `wit`, rather than using relative paths

### LINKED ISSUE #133: `wasi` subcrate is incompatible with `cargo vendor`
It is currently not possible to use `cargo vendor` in a project depending upon `wasi` subcrate from this repository

See https://github.com/rvolosatovs/wasi-vendor-repro for a reproducer

### PR DESCRIPTION
**Pull request by rvolosatovs**
This enables downstream builds utilizing `cargo vendor`, since `cargo vendor` resolves symlinks before packaging crates up

Closes #133

### CODE REVIEW

**Comment by rvolosatovs** [comment]
Thanks @ipetkov for 100% correct analysis of this https://github.com/ipetkov/crane/pull/271#issuecomment-1475387702

**Comment by rvolosatovs** [comment]
Alternative, and probably cleaner solution could be adopting something like https://github.com/rvolosatovs/depit once https://github.com/rvolosatovs/depit/issues/9 is implemented, such that the `host` crate could be self-contained while still benefiting from importing from the shared WIT definitions from the root of the repo

**Comment by rvolosatovs** [comment]
Alternative solution in https://github.com/bytecodealliance/preview2-prototyping/pull/136.

Symlinks AFAIK can be tricky on Windows, so https://github.com/bytecodealliance/preview2-prototyping/pull/136 should be a better option

**Comment by sunfishcode** [comment]
Yeah, I agree that symlinks can be tricky here. Fortunately #136 sounds like a good option.

**Comment by rvolosatovs** [comment]
Closing in favor of #136

**Pull request closed without merging**
