### PR TITLE
Start a preview2-to-preview1 polyfill.

### PR DESCRIPTION
**Pull request by sunfishcode**
To accompany the existing preview1-to-preview2 polyfill, add the start of a preview2-to-preview1 polyfill. It's somewhat rough and entirely untested at this point, but it's a start.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Could you expand a bit more on how this is supposed to be used? I'm not sure how this is expected to integrate into a build or otherwise take a component and compile it down to core wasm or something like that to use the old preview1 ABI.

**Comment by sunfishcode** [comment]
My rough idea here is that this would work with core modules using the canonical ABI, rather than encoded components.

But my other idea was that this can eventually serve to help illustrate how preview2 works, and possibly help engine implementors understand how preview2 will differ from their current preview1 implementations.

**Comment by alexcrichton** [comment]
As an illustration this seems fine, but I'm not sure it's actually feasible to execute this in any meaningful capacity. A bunch of core wasms can certainly be produced that all work with the canonical ABI but they can't actually get hooked up together. The component-model semantics of these functions are that data is copied between memories, and nothing's actually doing the copying so if the ABIs happen to line up then all the pointers are relative to someone else's memory.

That means actually executing this will require generating adapter core wasm modules like Wasmtime does for executing a component that internally links two components together. That isn't generally reusable at this time and this also can't go into wasmtime since a module that imports core wasm APIs like this can't be instantiated.

**Comment by sunfishcode** [comment]
Yeah, for Wasmtime we'll just implement preview2 directly, so we won't ever need this. This isn't at all urgent, so marking as a draft for now.

**Comment by sunfishcode** [comment]
Closing this as I'm not actively working on this.

**Pull request closed without merging**
