### PR TITLE
implement some filesystem primitives

### PR DESCRIPTION
**Pull request by pchickey**
## Host

Filled in trivial (in terms of WasiDir) implementations of the following host filesystem operations:

* `create_directory_at`
* `stat`
* `remove_directory_at`
* `symlink_at`
* `unlink_file_at`

## Tests

Switch `if true { /* TODO */ return Ok(()) }` short-circuiting logic to use `if EXPECT_FAIL` with a global constant, which makes it easier to run all tests to see which previously failing ones pass.

The following tests now appear to pass:
* `dangling_fd`
* `file_pread_pwrite`
* `file_unbuffered_write`
* `isatty`
* `path_exists`
* `symlink_create`

### CODE REVIEW

**Comment by sunfishcode** [comment]
The `file_sync_dir` failure on Windows is #66. But it appears `dangling_fd` is also failing.

**Comment by sunfishcode** [comment]
Overall though, the patch looks good! `EXPECT_FAIL` is good.

**Comment by pchickey** [comment]
I'll ignore file_sync_dir, and I set dangling_fd to ignore on windows for now.

I also fixed another minor bug in the test macro where every test was run twice.

**Comment by sunfishcode** [comment]
Nice! I had been wondering why those tests were running twice. Thanks for figuring it out!

**Pull request merged**
