### PR TITLE
Use the `wasi-stderr` API for stderr

### LINKED ISSUE #57: Command stderr being piped to wasi log
When running a WASI command under preview2, stderr is currently being piped to wasi log. This results in a couple of problems:

1. Each WASI log call is made individually, so buffered output that would usually appear on the same line is split over multiple lines and collated with potential log level / context info
2. This seems inconsistent with stdout running through wasi-poll write stream

### PR DESCRIPTION
**Pull request by sunfishcode**
Use the dedicated `wasi-stderr` API for stderr, instead of `wasi-logging`.

Fixes #57.

### CODE REVIEW

**Comment by sunfishcode** [comment]
I'm not yet sure this wasi-stderr API is a good idea, but it has the advantage of not having wasi-logging's expectation that each call represents a logical line of output.

Another option I considered was to have the polyfill buffer up output so that it could call wasi-logging with whole lines, but that reuqires picking a line length or accepting arbitrary buffer growth, and it doesn't play well with programs that use stderr for spinners/progress bars.

**Comment by sunfishcode** [comment]
A potential downside of this is that wasi-stderr is more awkward to implement on top of `console.log` in a Web context.

**Comment by guybedford** [comment]
Tried this out and I can confirm this resolves the issue in #57. Is there a reason not to use the existing wasi-poll `writeStream` path here?

That said, it does seem like this is closely tied to the problem in https://github.com/bytecodealliance/preview2-prototyping/issues/54 as well.

Another thing I was thinking is that perhaps we do just need some level of ambient control / configuration over the internal WASI state, for example to control log levels, descriptors etc separate from command invocation? That can be called as configuration exports of WASI or via some kind of adapter configuration at adapter time.

**Comment by sunfishcode** [comment]
I commented [here](https://github.com/bytecodealliance/preview2-prototyping/issues/57#issuecomment-1379678446) on the reason why this isn't using `writeStream`. One outcome of that is that stderr should always work reliably, even if stdout is somehow closed or otherwise failing.

For the log level control, I think we'll need to consider that in the context of specific use cases. For basic command-line apps, it seems sufficient to have a single config defined up front, but for other kinds of code, there may be other needs.

**Pull request merged**
